---
config:
  imagesPath: "./img/characters/"
characters:
  game:
    name: ""
    color: white
    style: 
      textCss:
        font-style: italic
  player:
    style:
      color: white 
      nameCss:
        color: red 
      textCss:
        color: white 
    sprites:
      idle: none
      invisible: none
    name: Vous
  unknown:
    style:
      color: white
      textCss:
        font-weight: bold
        color: white 
      nameCss:
        color: red
    sprites:
      invisible: none
      idle: whodat.webp
      scary: scary.webp
    name: VOIX MYSTÉRIEUSE
  jeuneFemme:
    style:
      color: white
      textCss:
        color: white 
      nameCss:
        color: red
    sprites:
      invisible: none
      idle: jeuneFemme.webp
    name: JEUNE FEMME EN BLANC
  dancer:
    style:
      color: white
      textCss:
        color: white
      nameCss:
        color: red
    sprites:
      invisible: none
      idle: dancer.webp
    name: LA DANSEUSE
  machin:
    style:
      color: white
      textCss:
        color: white 
      nameCss:
        color: red
    sprites:
      invisible: none
      idle: machin.webp
    name: HOMME DANS LE PUBLIC
  machine:
    style:
      color: white
      textCss:
        color: white 
      nameCss:
        color: red
    sprites:
      invisible: none
      idle: machine.webp
    name: FEMME DANS LE PUBLIC
